### ISSUE TITLE
Lesson 3 FireBase version 2.2.1

### ISSUE THREAD

**Issue by johanbove** [zoltan-nz/library-app#6]
First of all, thanks so much for this excellent tutorial!

In Lesson 3, we're integrating FireBase. It would be good to mention that the way FireBase is integrated into the tutorial has been deprecated as of version 3. Everything still works when installing FireBase version 2.2.1, so this should be mentioned in the tutorial.

```
npm install firebase-tools@2.2.1
```

**Comment by zoltan-nz** [comment]
Thank you, sounds good. I was waiting for the new release of the emberfire, which automatically install the new version, but you are right, this is a simple solution until the addon doesn't ready.

**Comment by johanbove** [comment]
Cool. I just realized this "issue" should have been created in the site repo, not in the code: yoember.github.io

So I'll close this here.

**Comment by ithinco** [comment]
@johanbove I guess I got the same error "FIREBASE WARNING: update at /invitations/-KJVdSbUqs9HMnH1NA5z failed: permission_denied", and `npm install firebase-tools@2.2.1` didn't work for me.:-(

BTW, thank you for your tutorial! @zoltan-nz

**Comment by zoltan-nz** [comment]
@ithinco is your database fully open or have you added some authentication, restriction to it already?

**Comment by ithinco** [comment]
@zoltan-nz I see...now it works, I changed the authentication rule of ".write" from "auth != null" to true.

**Comment by scooterlord** [comment]
Hello, a little late on the game, I thought I shouldn't open a new thread, since I think this one is related. Although I followed everything by the letter, I am getting an error. I installed emberfire, I created a firebase app, added the correct credentials in the environment config, set rules to public. I am getting this error:

`this.store.modelFactoryFor(...) is undefined getRecord@http://192.168.40.180:4200/assets/vendor.js:78127:22 createRecord@http://192.168.40.180:4200/assets/vendor.js:81748:18 saveInvitation@http://192.168.40.180:4200/assets/library-app.js:87:29 send@http://192.168.40.180:4200/assets/vendor.js:44948:28 handler/</<@http://192.168.40.180:4200/assets/vendor.js:24524:13 flaggedInstrument@http://192.168.40.180:4200/assets/vendor.js:31317:14 handler/<@http://192.168.40.180:4200/assets/vendor.js:24523:11 run@http://192.168.40.180:4200/assets/vendor.js:13264:16 run@http://192.168.40.180:4200/assets/vendor.js:35179:12 handler@http://192.168.40.180:4200/assets/vendor.js:24503:7 setupHandler/<@http://192.168.40.180:4200/assets/vendor.js:55080:15 dispatch@http://192.168.40.180:4200/assets/vendor.js:5523:16 add/elemData.handle@http://192.168.40.180:4200/assets/vendor.js:5332:6`

**Comment by zoltan-nz** [comment]
@scooterlord Thanks for your message, I double check. Which ember version do you use? 3.0? Maybe emberfire is still not compatible with the latest Ember. I check it out soon.

**Comment by scooterlord** [comment]
@zoltan-nz thanks for the swift reply! I am using ember-cli 2.13.2

**Comment by zoltan-nz** [comment]
Try to upgrade your ember project to Ember.js 2.18, basically, you should update package version numbers in package.json to be the same as in this repository.

Additionally, you can update your import syntax using this tool: https://github.com/ember-cli/ember-modules-codemod

**Comment by scooterlord** [comment]
..looks like I destroyed my project :/
