### ISSUE TITLE
Question on Query on has-many Attributes

### ISSUE THREAD

**Issue by li-xinyang** [zoltan-nz/library-app#7]
Is there a way to query on a `has-many` attributes? For example, I would like to query books that belong to an author which between certain publish date period.

```js
this.store.query('author', {orderBy: 'uid', equalTo: 'xxxxxxxx'})
  .then((records) => {
    return record.get('firstObject');
  }).then((author) => {
    author.store.query('book', {orderBy: 'publishDate', endAt: 'xxxx-xx-xx'});
  })
```

The code above seems works but it does not feel right. I look through the doc. but I could not find that I could not retrieve `store` from an Ember Data object.

My question is is there a way to query again on the Ember data object? 

Thanks for your time.

**Comment by zoltan-nz** [comment]
Thanks for your question, interesting story. Actually Firebase works a little bit differently than a normal Rest based Ember Data adapter. First of all the query language is a little bit unique. Secondly, because it is a realtime database almost always all query goes back to the server. It is not really Ember Data, it is more likely the Firebase Adapter, what the Firebase team created for Ember.js.

So if it works for you, you did well. Well done. :)

Firebase good for experimenting and learning, however if you would like to practice Ember Data, better if you create a mocked backend system with `ember-mirage`. In this tutorial we dig deeper in this topic: https://github.com/zoltan-nz/product-app, the "article" in Readme, I will move it soon to yoember. ;)
